export const CONCATENATE_TO_NUMBER = "CONCATENATE_TO_NUMBER";
export const STORE_NUMBER_TO_ARRAY = "STORE_NUMBER_TO_ARRAY";
export const ADD = "ADD";
export const SUBSTRACT = "SUBSTRACT";
export const MULTIPLY = "MULTIPLY";
export const DIVISION = "DIVISION";
export const EQUAL = "EQUAL";
export const CHANGE_DISPLAY_COLOR = "CHANGE_DISPLAY_COLOR";
export const REQUEST = 'REQUEST';
export const SUCCESS = 'SUCCESS';
export const FAILURE = 'FAILURE';
export const GET_ALL_ALBUMS_REQUEST = 'GET_ALL_ALBUMS_REQUEST';
export const GET_ALL_ALBUMS_SUCCESS = 'GET_ALL_ALBUMS_SUCCESS';
export const GET_ALL_ALBUMS_FAILURE = 'GET_ALL_ALBUMS_FAILURE';
export const INFO_ABOUT_AN_ALBUM = "INFO_ABOUT_AN_ALBUM";
export const GET_ALBUM_REQUEST = "GET_ALBUM_REQUEST";
export const GET_ALBUM_SUCCESS = "GET_ALBUM_SUCCESS";
export const GET_ALBUM_FAILURE = "GET_ALBUM_FAILURE";
export const GET_PHOTOS_REQUEST = "GET_PHOTOS_REQUEST";
export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";
export const GET_PHOTOS_FAILURE = "GET_PHOTOS_FAILURE";
export const CLEAR_PAGE = "CLEAR_PAGE";
export const GET_ALL_POSTS_REQUEST = "GET_ALL_POSTS_REQUEST";
export const GET_ALL_POSTS_SUCCESS = "GET_ALL_POSTS_SUCCESS";
export const GET_ALL_POSTS_FAILURE = "GET_ALL_POSTS_FAILURE";
export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const GET_POST_SUCCESS = "GET_POST_SUCCESS";
export const GET_POST_FAILURE = "GET_POST_FAILURE";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";
export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST";
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS";
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE";
export const POST_COMMENT_REQUEST = "POST_COMMENT_REQUEST";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";
export const PUT_COMMENT_REQUEST = "PUT_COMMENT_REQUEST";
export const PUT_COMMENT_SUCCESS = "PUT_COMMENT_SUCCESS";
export const PUT_COMMENT_FAILURE = "PUT_COMMENT_FAILURE";
export const PUT_POST_REQUEST = "PUT_POST_REQUEST";
export const PUT_POST_SUCCESS = "PUT_POST_SUCCESS";
export const PUT_POST_FAILURE = "PUT_POST_FAILURE";
export const GET_HOME_REQUEST = 'GET_HOME_REQUEST';
export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS';
export const GET_HOME_FAILURE = 'GET_HOME_FAILURE';
export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export default {
  CONCATENATE_TO_NUMBER,
  STORE_NUMBER_TO_ARRAY,
  ADD,
  SUBSTRACT,
  MULTIPLY,
  DIVISION,
  EQUAL,
  CHANGE_DISPLAY_COLOR,
  REQUEST,
  SUCCESS,
  FAILURE,
  GET_ALL_ALBUMS_REQUEST,
  GET_ALL_ALBUMS_SUCCESS,
  GET_ALL_ALBUMS_FAILURE,
  INFO_ABOUT_AN_ALBUM,
  GET_ALBUM_REQUEST,
  GET_ALBUM_SUCCESS,
  GET_ALBUM_FAILURE,
  GET_PHOTOS_REQUEST,
  GET_PHOTOS_SUCCESS,
  GET_PHOTOS_FAILURE,
  CLEAR_PAGE,
  GET_ALL_POSTS_REQUEST,
  GET_ALL_POSTS_SUCCESS,
  GET_ALL_POSTS_FAILURE,
  GET_POST_REQUEST,
  GET_POST_SUCCESS,
  GET_POST_FAILURE,
  GET_USER_REQUEST,
  GET_USER_SUCCESS,
  GET_USER_FAILURE,
  GET_COMMENTS_REQUEST,
  GET_COMMENTS_SUCCESS,
  GET_COMMENTS_FAILURE,
  POST_COMMENT_REQUEST,
  POST_COMMENT_SUCCESS,
  POST_COMMENT_FAILURE,
  PUT_COMMENT_REQUEST,
  PUT_COMMENT_SUCCESS,
  PUT_COMMENT_FAILURE,
  PUT_POST_REQUEST,
  PUT_POST_SUCCESS,
  PUT_POST_FAILURE,
  GET_HOME_REQUEST,
  GET_HOME_SUCCESS,
  GET_HOME_FAILURE,
  LOGOUT,
  LOGIN_SUCCESS,
  LOGIN_REQUEST,
  LOGIN_FAILURE,
  REGISTER_SUCCESS
};
